---
- name: Mediawiki install packages
  apt:
    name: "{{ mediawiki__default_packages }}"
    update_cache: yes
    state: present
  when: mediawiki__install

- name: Mediawiki remove autoinstalled(?) packages
  apt:
    name: "{{ mediawiki__default_remove_packages }}"
    update_cache: yes
    state: absent
  when: mediawiki__install

- name: MySQL/MariaDB user create
  mysql_user:
    name: "{{ mediawiki__conf.db_user }}"
    password: "{{ mediawiki__conf.db_password }}"
    priv: "{{ mediawiki__conf.db_name }}.*:ALL,GRANT"
    host: "%"
    login_user: "{{ mediawiki__conf.db_admin_user }}"
    login_password: "{{ mediawiki__conf.db_admin_password }}"
    login_host: "{{ mediawiki__conf.db_host }}"
  when:
    - mediawiki__install
    - mediawiki__configure

- name: MySQL/MariaDB db create
  mysql_db:
    name: "{{ mediawiki__conf.db_name }}"
    login_user: "{{ mediawiki__conf.db_admin_user }}"
    login_password: "{{ mediawiki__conf.db_admin_password }}"
    login_host: "{{ mediawiki__conf.db_host }}"
  when:
    - mediawiki__install
    - mediawiki__configure

- name: Create apache service file
  template:
    src: vhost.conf
    dest: "/etc/apache2/sites-available/{{ mediawiki__conf.hostname }}"
  notify: Reload apache2 service
  when:
    - mediawiki__install
    - mediawiki__configure

- name: Create apache2 link service file
  file:
    path: "/etc/apache2/sites-enabled/{{ mediawiki__conf.hostname }}.conf"
    src: "/etc/apache2/sites-available/{{ mediawiki__conf.hostname }}"
    state: link
  notify: Reload apache2 service
  when:
    - mediawiki__install
    - mediawiki__configure

- name: Activate apache2 ssl module
  apache2_module:
    ignore_configcheck: yes
    name: ssl
    state: present
  notify: Reload apache2 service
  ignore_errors: True
  when:
    - mediawiki__install
    - mediawiki__configure
    - mediawiki__use_ssl

- name: Create LocalSettings mediawiki file
  template:
    src: LocalSettings.php
    dest: "/etc/mediawiki/LocalSettings.php"
  when:
    - mediawiki__install
    - mediawiki__configure

